# server/bot.py
"""
Discord Bot Integration Module.
Listens to a designated Discord channel, intercepts messages, handles mapping overrides 
(like those generated by the Scriptly bot), logs rolls, and pushes the dialogue to the Flask backend.
"""
import discord
import re
import csv
import os
import aiohttp 
from dotenv import load_dotenv

# Initialize environment variables to securely retrieve the Discord token.
load_dotenv() 
TOKEN = os.getenv('DISCORD_TOKEN')

# Configure Discord intents. message_content is strictly required to read the text of user messages.
intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents=intents)

# The specific Discord channel ID the bot will monitor. It ignores all other channels.
TARGET_CHANNEL_ID = 1539453159087411231 

# Regex to detect and extract Avrae or custom dice roll formats (e.g., "Action: Attack - Roll: 18").
ROLL_REGEX = re.compile(r'Action:\s*(.*?)\s*-\s*Roll:\s*(\d+)')

# Regex to catch and parse messages forwarded by the 'Scriptly' Tupper/Webhook bot.
# Extracts the original author's name and the core message content.
SCRIPTLY_REGEX = re.compile(r"\[\d+:\d+\s?[AP]M\]\s+APP\s+\[Scriptly\]\s+([\w\.]+)\s*:\s*(.+)")

# Initialize the local CSV log file and write the header row if the file does not already exist.
if not os.path.exists('live_log.csv'):
    with open('live_log.csv', mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['Timestamp', 'User', 'Action_Taken', 'Dice_Roll', 'Full_Raw_Text'])

@client.event
async def on_ready():
    """
    Lifecycle event triggered when the bot successfully connects to the Discord API.
    """
    print(f'🟢 {client.user.name} is online and listening!')
    print(f'Monitoring channel ID: {TARGET_CHANNEL_ID}')
    print('------')

@client.event
async def on_message(message):
    """
    Lifecycle event triggered on every single message visible to the bot across all servers.
    """
    # Prevent infinite loops by ensuring the bot never processes its own messages.
    if message.author == client.user: 
        return
        
    # Strictly enforce that only messages from the designated gameplay channel are processed.
    if message.channel.id != TARGET_CHANNEL_ID: 
        return

    # Extract base author and content.
    author_name = message.author.name
    content = message.content

    # If the message matches the Scriptly webhook format, override the author and content
    # with the regex-extracted data to get the actual player's name and intent.
    scriptly_match = SCRIPTLY_REGEX.search(content)
    if scriptly_match:
        author_name = scriptly_match.group(1).strip()
        content = scriptly_match.group(2).strip()

    print(f"\n💬 [DEBUG - DISCORD BOT] Caught message from {author_name}: {content}")

    # Initiate an asynchronous HTTP session to push the parsed message to the local Flask application.
    async with aiohttp.ClientSession() as session:
        payload = {
            "author": author_name,
            "content": content,
            "timestamp": message.created_at.isoformat()
        }
        print(f"🚀 [DEBUG - DISCORD BOT] Sending POST payload to app.py: {payload}")
        try:
            # Send POST request to the local Flask ingest endpoint.
            async with session.post("http://127.0.0.1:5001/api/live_chat_ingest", json=payload) as resp:
                print(f"✅ [DEBUG - DISCORD BOT] Flask Responded with Status: {resp.status}")
                
                # Log any non-success HTTP codes for debugging.
                if resp.status != 200:
                    err_text = await resp.text()
                    print(f"⚠️ [DEBUG - DISCORD BOT] Error response body: {err_text}")
        except Exception as e:
            print(f"❌ [DEBUG - DISCORD BOT] Failed to forward message to Flask App. Is app.py running? Error: {e}")

    # Check if the message contains a dice roll. If so, parse the action/roll and log it to the CSV.
    roll_match = ROLL_REGEX.search(content)
    if roll_match:
        # Strip newlines from the raw text to prevent CSV row corruption.
        clean_text = re.sub(r'\n+', ' ', content)
        with open('live_log.csv', mode='a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow([
                message.created_at.strftime("%Y-%m-%d %H:%M:%S"),
                author_name,
                roll_match.group(1),
                roll_match.group(2),
                clean_text
            ])
        print(f"✅ [DEBUG - DISCORD BOT] Logged roll to CSV from {author_name}")

# Standard execution guard to ensure the token exists before launching the connection.
if TOKEN is None:
    print("❌ Error: DISCORD_TOKEN not found.")
else:
    client.run(TOKEN)